apiVersion: apps/v1
kind: Deployment
metadata:
  name: ion-deployment
  labels:
    app: ion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ion
  template:
    metadata:
      labels:
        app: ion
    spec:
      containers:
      - name: ion
        image: mohammadsohail558/dckr-repo:v2.0
        ports:
        - containerPort: 80
